### ISSUE TITLE
Error since updating to 0.5.2

### ISSUE THREAD

**Issue by fireman644** [shemetz/pf2e-crowdsourced-community-corrections#2]
foundry.js:655 Error: An error occurred while rendering CorrectionsMenu 32. ENOENT: no such file or directory, open 'D:\FoundryVTT v12\Data\modules\pf2e-crowdsourced-community-corrections\templates\correctionsMenu.hbs'
[No packages detected]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.js:5795:13
onError @ foundry.js:655
🎁Hooks.onError#0 @ libWrapper-wrapper.js:188
(anonymous) @ foundry.js:5795
Promise.catch (async)
render @ foundry.js:5793
onClickSubmenuWrapper @ colorSetting.js:21
🎁call_wrapper @ libWrapper-wrapper.js:614
🎁SettingsConfig.prototype._onClickSubmenu#0 @ libWrapper-wrapper.js:193
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

I tried both v51 and v52 and get his error.  Didn't occur before updating. Hope this help thanks.

**Comment by shemetz** [comment]
Should be fixed now in v0.5.3, please let me know if it isn't (and thanks for trying out the module)

**Comment by fireman644** [comment]
Yep that did it thank you!

Sean G.
